### ISSUE TITLE
Help: Explanation of result of 988KB file split

### ISSUE THREAD

**Issue by Sampath-Lokuge** [qrclip/capacitor-file-chunk#13]
Hi,

I have used the below code to split my sample 988KB SQLite DB file on the Ionic/Angular/Capacitor native app. 
I wonder why it gives 4MB size array items for that? I would like to understand what is happening here. Thanks!

```
private async splitOldCordovaDatabase(): Promise<void> {
    const tPath = '/data/user/0/test/databases/data.db';
    const tOffset = 0;
    const tLength2Read = 4194304; //4MB

    const tArray = await this.mFileChunkManager.readFileChunkFS(tPath, tOffset, tLength2Read);
    console.log(`tArray`, tArray);
  }
```

Result:
![1](https://github.com/qrclip/capacitor-file-chunk/assets/5206526/d1263c14-742b-4ece-9c9e-456076eef7d3)

**Comment by qrclip** [comment]
Hello,
You need to know the file size and you can't read more than that. It's in the documents. I made this decision so that I don't have to check the file size every time I call it up.

Basically I just read the file size and nothing else.

Thank you,

**Comment by Sampath-Lokuge** [comment]
Hi,

Can I have help to write the above method with after check the file size? i.e. correct way of it. Thanks!

**Comment by qrclip** [comment]
just use this function on the manager:
 public async checkFileSize(tPath: string): Promise<number> 
 to check the file size

**Comment by Sampath-Lokuge** [comment]
I think this is fine now no.

```
 private async splitOldCordovaDatabase(): Promise<void> {
    const tPath = '/data/user/0/com.siness.ximateapp/databases/data.db';
    const tOffset = 0;
    const tLength2Read = 4194304; //4MB
    let tArray: Uint8Array;

    const tFileSize = await this.mFileChunkManager.checkFileSize(tPath);

    if (tFileSize <= tLength2Read) {
      tArray = await this.mFileChunkManager.readFileChunkFS(tPath, tOffset, tFileSize);
    } else {
      tArray = await this.mFileChunkManager.readFileChunkFS(tPath, tOffset, tLength2Read); //over 4MB
    }

    console.log(`tArray`, tArray);
  }
```

**Comment by qrclip** [comment]
check here:
https://github.com/qrclip/capacitor-file-chunk/blob/main/demo/src/app/benchmark/benchmark.page.ts

this function:
private async testStepReadAllTestFile(

You have to deal with multiple chunks, you are not handling chunks. Is your database file larger than 10 MB? for example?

In this example, the file size is read in chunks, you have to assemble them into one after reading each array.

**Comment by Sampath-Lokuge** [comment]
> Is your database file larger than 10 MB? 

Yes, it is around 1GB

> In this example, the file size is read in chunks, you have to assemble them into one after reading each array.

I didn't get this. I need to send this file to Azure Blob storage through the backend API. So how to prepare it for that use case? Any help would be highly appreciated. Thanks!

**Comment by qrclip** [comment]
Hello,
You need to read the file in chunks, I'm not familiar with Azure. 
But basically you need to proceed as follows:
Read the file in chunks of 10 MB. That's the sweet spot. Merge them into 50 MB arrays (I don't know the optimal Azure size) and post each array to Azure. I suspect there is a muitpart upload like with s3. You shouldn't read 50 MB chunks from a take, as this will probably crash some Android phones. 10 MB will work on almost any device.

this plugin only reads the file in chunks, what you do with the data is up to you.

**Comment by Sampath-Lokuge** [comment]
Hi,

Ok sure. I'll see that. One final question here. 

 `const tPath = '/data/user/0/com.my.testpp/databases/data.db';`

Above is my DB path inside the Android device. Can I give that path directly to a C# web API as a path for the file? I have asked this hence this is related to the native app's file path. Thanks!

**Comment by qrclip** [comment]
Sorry, I didn't understand your question. You want to send a local path to a REST API?

**Comment by Sampath-Lokuge** [comment]
Yes, How can I construct this path for that? i.e. need a full path for that. 
>const tPath = '/data/user/0/com.my.testpp/databases/data.db';

**Comment by qrclip** [comment]
You can't do that because the REST API can't access your phone data directly. To send a file, for example to make a POST or PUT request, you must have already read the data into memory or streamed it.

**Comment by Sampath-Lokuge** [comment]
Yes, you're right. May I know how I can do that? i.e. get a stream of the above database file and then send it to the API directly.

**Comment by Sampath-Lokuge** [comment]
Any reason why this gives `Error: File does not exist`. Is that path wrong?

I have given too.
```

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

 ```
private async streamDatabaseFile(): Promise<void> {
    const dbFilePath = '/data/app-id/databases/data.db'; 

    const { data } = await Filesystem.readFile({
      path: dbFilePath,
      directory: Directory.Data, // Use the appropriate directory
      encoding: Encoding.UTF8, // Adjust encoding if needed
    });

    console.log(`data`, data);
  }
```

**Comment by Sampath-Lokuge** [comment]
I have put more info here. Please see that too. https://stackoverflow.com/questions/78507290/create-a-stream-from-the-sqlite-database-file-to-send-that-stream-to-c-sharp-web

**Comment by qrclip** [comment]
That path is clearly wrong. Please read the documentation of the capacitor file system and watch some tutorials. You are trying to do things without knowing the proper basics, and trying to brute force a solution. Try to make small steps, create a file, write to it and read it.
The things you are asking about are outside the scope of this plugin.
Thanks,
