### ISSUE TITLE
How to read file that has been downloaded in external storage in chunk, and unzip it properly.

### ISSUE THREAD

**Issue by akshar-bk** [qrclip/capacitor-file-chunk#15]
Hi,
I am using a ionic 7, capacitor v 5.
I have use case where I am downloading a file from s3 to my external android storage using downloadFile Capacitor Filesystem.
However, the zip file download is completed but when I try to read the file using FileSystem read file, because i want to unzip the file.
But my app is crashing because of memory issue, javaoutofbound memory array is thrown I check this on logcat android.
So using this plugin how should I proceed so that I can read the file in chunk and unzip it properly.
Thanks

**Comment by qrclip** [comment]
The only option is to download the files in chunks and unzip and save each chunk without storing the entire contents in memory. This way the memory consumption will be low. If that's the only thing you need to do, you don't need this plugin. You can use the capacitor file system and append to the file.

**Comment by akshar-bk** [comment]
Thanks for the reply @qrclip 
But download file function works properly, it downloads the file, but app is crashing when it tries to read the file using readFile filesystem API.

**Comment by akshar-bk** [comment]
I have a usecase, where I want to download zip file stored in S3 file size can be larger than 100mb, I also have to unzip it properly and store it in Directory.Data of android.
@qrclip How would you approach this efficiently?

**Comment by qrclip** [comment]
But maybe you should try downloading from s3 in chunks instead of saving the whole file, and then save only the uncompressed data. If the file is so big that you can't have it in memory, it will crash.

**Comment by akshar-bk** [comment]
@qrclip Thank you. I wil try and update you
