### ISSUE TITLE
Can I do simultaneous downloads?

### ISSUE THREAD

**Issue by Naerian** [qrclip/capacitor-file-chunk#4]
Hi!

Im trying to do simultaneous downloads and I got this instancing "FileChunkManager" in each item separately. But when finish first item and call "stopServer" all of the rest download finish too..

Can I do something to avoid stopping the rest of the downloads?

**Comment by Naerian** [comment]
I can answer myself:

Using random number between 1024 - 65535, u can generate a random port number and use it in "port" attribute when start server. This way u can launch multiple downloads with differentes port and stopped them separately.

**Comment by qrclip** [comment]
Hello,

Yes, this is the solution. Although it was not designed with concurrency in mind, it should work.

Thanks!
