### ISSUE TITLE
Question: Uploading Multiple Large Files From Capacitor

### ISSUE THREAD

**Issue by AdlerJS** [qrclip/capacitor-file-chunk#5]
Hey There. Just wanted to clarify something and then I will close this issue but this plugin seems to fit a need I've been wanting for a long time. Per the ReadMe you state

Uploading large files
Efficiently upload large files in Capacitor applications by reading parts of a file and uploading them in chunks. This method reduces the risk of timeouts and network errors, ensuring seamless uploading of large files for users without any loss of data or performance issues. Note that the actual implementation depends on the server and how the files are stored.

So just wanted to follow up on this. The need of our application right now is given a array of file paths (we use capacitor-file-picker) to grab the file paths. Can I upload the files directly to lets say azure or aws in chunks directly from this plugin without needing to read the file into memory?

Right now what we do is read the file into memory using fetch(nativeFilePath) and then use https://github.com/23/resumable.js to upload the file to our server in chunks. It seems like this plugin could offer a much more performant alternative to this approach but just wanted to ask here before investing a ton of time in the implementation.

**Comment by qrclip** [comment]
Hello,

Yes, it's a good solution as long as you can somehow upload the files in chunks. You can easily read and write chunks with it. What you then do with these chunks is up to you. There are two modes: the fast one with the web server and the slow one with the capacitor bridge. Both methods allow you to read and write with chunks. The web server or localhost mode is many times faster, but the problem with that is when the app goes into the background. On Android, it depends on the Android version, but on iOS, the server shuts down immediately when the app goes into the background. I still haven't found a way to keep the app running, but I haven't lost too much time yet. If you need help, ask here or send an email to antero [at] qrclip.io

Thanks!
