### ISSUE TITLE
Help: Upload SQLite db around 1GB to the Azure blob storage

### ISSUE THREAD

**Issue by Sampath-Lokuge** [qrclip/capacitor-file-chunk#7]
Hi,

I would like to have some support from you here about my use case.

I need to upload SQLite db around 1GB to the Azure blob storage. That file is in `Directory.Data` folder. I use .net APIs as the backend. Please let me know the steps to use your plugin for my use case. Thanks!

`P.S.` I have an Ionic/Angular native mobile app.

```
 "@capacitor/core": "5.2.3",
 "@ionic/angular": "7.3.4",
```

**Comment by qrclip** [comment]
Hello,

To upload the file to Azure blob storage, you need to read it in 4MB blocks and then upload each block using block blobs.
You can read more about it here:
https://medium.com/@vitalijus.alsauskas/upload-files-in-chunks-to-azure-blob-storage-using-azure-rest-api-b6770fb52a08
 or search for upload to azure blob in chunks for better instructions.

Thanks,

**Comment by Sampath-Lokuge** [comment]
Hi,

Thanks a lot for the info!

Do you have an example for this use case on your plugin's demo app? :https://github.com/qrclip/capacitor-file-chunk?tab=readme-ov-file#uploading-large-files

i.e.:

Uploading large files
Efficiently upload large files in Capacitor applications by reading parts of a file and uploading them in chunks. This method reduces the risk of timeouts and network errors, ensuring seamless uploading of large files for users without any loss of data or performance issues. Note that the actual implementation depends on the server and how the files are stored.

I have found this article and it requires `The chunked upload Action method receives the Chunk or Block number from the client along with the Slice of file that needs to be uploaded in the Request. `. So how can I get it from your plugin? Please let me know. Thanks!

Article: https://www.dotnetcurry.com/aspnet-mvc/893/upload-big-files-aspnet-mvc-azure-storage

**Comment by qrclip** [comment]
I'm not familiar with Azure Blob Storage and can't read the documentation now to give reliable information. But I asked chatgpt, this is untested, but it looks ok.

```
// Example function that uploads a chunk to Azure Blob Storage
// You will need to implement this according to your Azure Blob Storage setup
async function uploadChunkToAzure(containerClient: any, blobName: string, chunkData: Uint8Array, offset: number): Promise<void> {
  const blockId = window.btoa(offset.toString()).replace(/=/g, '');
  await containerClient.getBlockBlobClient(blobName).stageBlock(blockId, chunkData, chunkData.length);
}


//
 public async uploadFileInChunks(filePath: string, blobName: string, chunkSize: number) {
    // Initialize your Azure Blob Service Client and Container Client
    const blobServiceClient = BlobServiceClient.fromConnectionString('Your_Azure_Storage_Connection_String');
    const containerClient = blobServiceClient.getContainerClient('Your_Container_Name');

    // Get the file size first to ensure we do not read beyond it
    const fileSize = await this.mFileChunkManager.checkFileSize(filePath);
    let offset = 0;
    let continueReading = true;

    while (continueReading) {
      // Calculate the size to read, ensuring it does not exceed the file size
      const remainingSize = fileSize - offset;
      const sizeToRead = Math.min(chunkSize, remainingSize);

      if (sizeToRead > 0) {
        const chunkData = await this.mFileChunkManager.readFileChunkFS(filePath, offset, sizeToRead);

        if (chunkData) {
          // Upload the chunk to Azure Blob Storage
          await uploadChunkToAzure(containerClient, blobName, chunkData, offset);

          // Move the offset ahead by the size we just read
          offset += sizeToRead;
        } else {
          // If chunkData is null or empty, stop reading
          continueReading = false;
        }
      } else {
        // No more data to read
        continueReading = false;
      }
    }

    // After all chunks are uploaded, commit them to create the blob
    await containerClient.getBlockBlobClient(blobName).commitBlockList(/* You'll need to provide the list of block IDs you used */);
  }
```
