### ISSUE TITLE
Help: Access custom path like databases

### ISSUE THREAD

**Issue by Sampath-Lokuge** [qrclip/capacitor-file-chunk#8]
Hi,

Please let us know how to access the custom path like so:

![1](https://github.com/qrclip/capacitor-file-chunk/assets/5206526/3dea1abc-c2b7-4d7d-8bf7-13fa855fd28b)

I have tried this: 

`const tUri = await this.mFileChunkManager.getPath('/databases/data.db', Directory.Data);`

It gives this wrong path:

`/data/user/0/com.app.c/files/databases/data.db`

But the actual path is this: i.e. no `files/`

`/data/user/0/com.app.c/databases/data.db`

Thanks!

**Comment by qrclip** [comment]
Hello,

getPath returns a string. If you know the path, you don't need to use it. Use the string directly. In your case "/data/user/0/com.app.c/databases/data.db" 

Thank you!

**Comment by Sampath-Lokuge** [comment]
Ok sure. Thanks!
