### ISSUE TITLE
Support Needed with readFileChunkFS

### ISSUE THREAD

**Issue by rmakash** [qrclip/capacitor-file-chunk#9]
Dear Team,
First I want to thank you all for the great efforts to create and support such a great plugin.
I'm trying to read a video/image file higher than 300MB! The file is saved locally on my iOS device. I'm using IONIC FilePicker.pickMedia to select the file using iOS and Android. 

The FilePicker result is as follow:
{"files":[{"width":1080,"size":179743134,"path":"file:\/\/\/Users\/raed\/Library\/Developer\/CoreSimulator\/Devices\/CA37934A-793D-43B1-91A0-2FFD564127B3\/data\/Containers\/Data\/Application\/64B1D54F-C9C8-4B27-8FAB-53299BEE63AE\/Library\/Caches\/69953DF7-

this.files[0].path =  file:///Users/raed/Library/Developer/CoreSimulator/Devices/CA37934A-793D-43B1-91A0-2FFD564127B3/data/Containers/Data/Application/64B1D54F-C9C8-4B27-8FAB-53299BEE63AE/Library/Caches/69953DF7-CF9A-4AA9-B585-C7C327F5C646/11-400797E5-3133-47DD-8C1A-70568D672E28.mov

Using this.mFileChunkManager.getPath(image.path!, Directory.Library) the result is :
/Users/raed/Library/Developer/CoreSimulator/Devices/CA37934A-793D-43B1-91A0-2FFD564127B3/data/Containers/Data/Application/64B1D54F-C9C8-4B27-8FAB-53299BEE63AE/Library/file:///Users/raed/Library/Developer/CoreSimulator/Devices/CA37934A-793D-43B1-91A0-2FFD564127B3/data/Containers/Data/Application/64B1D54F-C9C8-4B27-8FAB-53299BEE63AE/Library/Caches/69953DF7-CF9A-4AA9-B585-C7C327F5C646/11-400797E5-3133-47DD-8C1A-70568D672E28.mov

No matter what I provide for this.mFileChunkManager.readFileChunkFS(filePath, this.tOffset, this.tLength)
The result is always an empty Array!!

Appreciate all the help that I get from your side.

**Comment by qrclip** [comment]
Hello,

Are you sure the path is correct? It looks like a directory from your macOS instead of a cell phone.

**Comment by rmakash** [comment]
Hello,
Thank you for taking the time to check and follow on this ticket.
The path looks like this because I'm testing the development using a simulator.
I hope this helps.

**Comment by qrclip** [comment]
Even in the simulator you have to use the right path, like on a real device, it doesn't matter. I'm almost 100% sure this will never work. Can you open a file with this path with the capacitor file system?

**Comment by rmakash** [comment]
Thanks,
Let me try it using a real device and I'll keep you posted.
While I have your attention just want to confirm that even-though I'm using the readFileChunkFS function do I still need to make sure that the localhost server is running (mFileChunkManager.startServer)?
As for your question about if I can open a file with this path using capacitor file system. please be informed that I was able to read the file using such path using Filesystem.readFile function.

**Comment by qrclip** [comment]
You do not need to initialize the server to use this function. 
It also works in the simulator. Simply use a normal device path, e.g. a file in the Documents or App Data folder.

**Comment by rmakash** [comment]
Hello,
I used a real iOS device and below please find the console log:
PS. I used mFileChunkManager.checkFileSize to check If I can get the file size using the provided path and I was able to read the file size but still the readFileChunk is still empty array!! 

⚡️  To Native ->  Filesystem stat 13641735
⚡️  TO JS {"mtime":"1706980030326","uri":"file:\/\/\/var\/mobile\/Containers\/Data\/Application\/6285183A-CB22-439A-B484-5D32B8B3F5F5\/Library\/Caches\/78B67FD7-6B39-456B-B61D-BCB7343A95D6\/RPReplay_Final1706980029.mp4","ctime":"1706980029541","type":"file","size":1
⚡️  [log] -  ** mFileChunkManager.checkFileSize =  11478904
⚡️  [log] - ** File Path =  file:///var/mobile/Containers/Data/Application/6285183A-CB22-439A-B484-5D32B8B3F5F5/Library/Caches/78B67FD7-6B39-456B-B61D-BCB7343A95D6/RPReplay_Final1706980029.mp4
⚡️  [log] -  ** mFileChunkManager.checkFileSize =  11478904
⚡️  To Native ->  FileChunk readFileChunk 13641736
⚡️  TO JS {"data":""}

**Comment by qrclip** [comment]
I need to see more code to see the problem, what values you are giving to readFileChunkFS?

**Comment by rmakash** [comment]
Hello,
Once again appreciate all the help that i'm getting from your end.
According to your request please find below the code that I'm using.

import { Component, ElementRef, OnInit, ViewChild, Input, OnDestroy } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { FileChunkManager } from '../../file-chunk-manager/file-chunk.manager';
import { LoadingController, Platform } from '@ionic/angular';
import { FilePicker, FilePickerPlugin, PickedFile } from '@capawesome/capacitor-file-picker';
import { Filesystem, Directory, Encoding } from '@capacitor/filesystem';
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
import { PostService } from 'src/app/services/post.service';
import { DownloadFetchRange } from './download-fetch-range';
import { Subject, takeUntil } from 'rxjs';
import { ToastController } from '@ionic/angular';
@Component({
  selector: 'app-file-picker',
  templateUrl: './file-picker.page.html',
  styleUrls: ['./file-picker.page.scss'],
})
export class FilePickerPage implements OnInit {
@Input() mUrl = 'https://cdn.qrclip.io/dev/pi.zip'; // THIS IS NOT A ZIP (BUT CORS WAS NOT WORKING WITH TEXT FILES)
 @Input() mFilename = this.getFilenameFromUrl(this.mUrl);
mDownloadFetchRange: DownloadFetchRange = new DownloadFetchRange();


  skipTranscoding:any = true;
  readData: any = false;
  multiple:any = false;
  
  async pickMediaFile (){
    const multiple = this.multiple;
    const readData = this.readData;
    const skipTranscoding = this.skipTranscoding;
    const result =  await FilePicker.pickMedia({
      multiple: multiple,
      readData: readData,
      skipTranscoding: skipTranscoding,
    });
    // Get the file size first to ensure we do not read beyond it
    const fileSize = await this.mFileChunkManager.checkFileSize(result.files[0].path!);
    let offset = 0;
    let continueReading = true;
    let chunkSize = 10024000;
    while (continueReading) {
      // Calculate the size to read, ensuring it does not exceed the file size
      const remainingSize = fileSize - offset;
      const sizeToRead = Math.min(chunkSize, remainingSize);
      console.log('** sizeToRead =',sizeToRead);
      if (sizeToRead > 0) {
        const chunkData = await this.mFileChunkManager.readFileChunkFS(result.files[0].path!, offset, sizeToRead);
        if (chunkData) {
          console.log('** chunkData = ',chunkData);
        /** Handle Other function to upload chunkData as file to server ***/
          offset += sizeToRead;
        } else {
          // If chunkData is null or empty, stop reading
          continueReading = false;
        }
      } else {
        // No more data to read
        continueReading = false;
        console.log('*** readFileChunkFS Done');
      }
    }
  }

**Comment by qrclip** [comment]
This can only be a permission issue, the plugin does not request permission, you need to be sure you have permission to read the file, I have never tested this with FilePicker. In my app I only use the plugin to receive shared files from other apps. Can't you see if there is an error on the console that is not from capacitor but from ios itself? If there is an permission problem, it should be visible there.

**Comment by rmakash** [comment]
Hi,
For sure I do have the function that check and request permission if needed.
I can assure you that I have permission to read the file using the FilePicker.pickMedia function.
The code contain more than one function and permission request is being handled in another function.
I only provided the function part that deal with   mFileChunkManager.readFileChunkFS.
I hope this helps.

**Comment by qrclip** [comment]
Can you try to create a file in the app cache directory and read it? I can't see anything else with the information available. You can also try to go to the ios plugin code and debug there.

FileChunkPlugin.swift

at this function:

@objc func readFileChunk(_ call: CAPPluginCall) {

​I would try this above all to check whether I get a "fileHandle"

**Comment by rmakash** [comment]
Dear Team,
I thank you for all the great efforts in supporting such a great plugin. I followed your instructions and I was able to get the problem fixed. Your plugin works like magic.
I only faced a problem with reading/chunking files that contain a space in the file name!!
Below please find the log for a script that i wrote to create, read and chunk a TXT file, the file nam is (first file.txt).

⚡️  [log] - **** Start writing file
⚡️  To Native ->  Filesystem writeFile 83010167
⚡️  TO JS {"uri":"file:\/\/\/Users\/raed\/Library\/Developer\/CoreSimulator\/Devices\/E20C6D32-DDFA-426D-81E2-981834723F8B\/data\/Containers\/Data\/Application\/E405103E-2EC5-4BEE-A2D6-EB1EC8ADC36E\/Documents\/first%20file.txt"}

⚡️  To Native ->  Filesystem readFile 83010168
⚡️  [log] - {"uri":"file:///Users/raed/Library/Developer/CoreSimulator/Devices/E20C6D32-DDFA-426D-81E2-981834723F8B/data/Containers/Data/Application/E405103E-2EC5-4BEE-A2D6-EB1EC8ADC36E/Documents/first%20file.txt"}
⚡️  TO JS {"data":"One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided b
⚡️  To Native ->  Filesystem readFile 83010169
⚡️  TO JS {"data":"T25lIG1vcm5pbmcsIHdoZW4gR3JlZ29yIFNhbXNhIHdva2UgZnJvbSB0cm91YmxlZCBkcmVhbXMsIGhlIGZvdW5kIGhpbXNlbGYgdHJhbnNmb3JtZWQgaW4gaGlzIGJlZCBpbnRvIGEgaG9ycmlibGUgdmVybWluLiBIZSBsYXkgb24gaGlzIGFybW91ci1saWtlIGJhY2ssIGFuZCBpZiBoZSBsaWZ0ZWQgaGlzIGhlYWQgYSBsaXR

⚡️  To Native ->  Filesystem getUri 83010170
⚡️  TO JS {"uri":"file:\/\/\/Users\/raed\/Library\/Developer\/CoreSimulator\/Devices\/E20C6D32-DDFA-426D-81E2-981834723F8B\/data\/Containers\/Data\/Application\/E405103E-2EC5-4BEE-A2D6-EB1EC8ADC36E\/Documents\/first%20file.txt"}
⚡️  To Native ->  Filesystem stat 83010171
⚡️  TO JS {"ctime":"1709115339817","uri":"file:\/\/\/Users\/raed\/Library\/Developer\/CoreSimulator\/Devices\/E20C6D32-DDFA-426D-81E2-981834723F8B\/data\/Containers\/Data\/Application\/E405103E-2EC5-4BEE-A2D6-EB1EC8ADC36E\/Documents\/first%20file.txt","size":2614,"m

⚡️  To Native ->  FileChunk readFileChunk 83010172
** tPath **
/Users/raed/Library/Developer/CoreSimulator/Devices/E20C6D32-DDFA-426D-81E2-981834723F8B/data/Containers/Data/Application/E405103E-2EC5-4BEE-A2D6-EB1EC8ADC36E/Documents/first%20file.txt
⚡️  TO JS {"data":""}
⚡️  [log] - {"data":""}

**Comment by qrclip** [comment]
Good to know, I'll take a look. Now that you bring it up, I'm almost certain I've tested it, but my filenames always have no spaces, an old habit that's bad for these situations(testing). It would be extremely easy to miss, as I haven't used spaces in filenames for many years :D
